my_blog/urls.py
from django.contrib import admin
from django.urls import include,path,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from article.views import article_list

urlpatterns = [
    path("",article_list,name="home"),
    path("admin/", admin.site.urls),
    path("article/", include("article.urls",namespace="article")),
    path('userprofile/', include('userprofile.urls',namespace='userprofile')),
    path('comment/', include('comment.urls',namespace='comment')),
    # 这里的notifications.urls没有像之前一样用字符串，是为了确保模块安装到正确的命名空间中。
    path('inbox/notifications',include(notifications.urls,namespace='notifications')),
    # notice
    path('notice/',include('notice.urls',namespace='notice')),
    # allauth的登录，也是一个单独的APP
    path('accounts/', include('allauth.urls')),

    # 部署时使用，让gunicorn知道static和media文件在哪
    re_path(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

#添加这行为以后上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

app_name='notice'

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>',views.user_delete,name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

userprofile/models.py
#用于支持一些models的操作
from django.db import models
# 引入django自带的User模块
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save
# 引入信号接收器的装饰器
from django.dispatch import receiver


# 用户扩展信息
class Profile(models.Model):
    # 与 User 模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 电话号码字段
    phone = models.CharField(max_length=20, blank=True)
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender,instance, created,**kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()

userprofile/forms.py
# 引入表单类
from django import forms
# 引入User模型
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile
from django.contrib.auth.forms import UserCreationForm


# 登录表单，继承了forms.Form类，不与数据库直接接触。
class UserLoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class UserRegisterForm(UserCreationForm):

    email = forms.EmailField(label="Email")

    class Meta:
        # 表示模型来自django自带的User
        model = User
        #展示的字段
        fields = ['id','username', 'email']

# 新建一个表单以编辑用户信息
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .forms import UserLoginForm,UserRegisterForm,ProfileForm
from .models import Profile

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # clean_data 清洗出合法数据
            data = user_login_form.cleaned_data
            #检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个user对象
            user = authenticate(username = data['username'],password = data['password'])
            if user:
                # 将用户数据保存在session中，即实现登录动作
                login(request,user)
                return redirect('article:article_list')
            else:
                return HttpResponse('用户名或密码错误')
        else:
            return HttpResponse('用户名或密码输入不合法')
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context={'user_login_form':user_login_form}
        return render(request,'userprofile/login.html',context)
    else:
        return HttpResponse('请使用GET或者POST请求')

def user_logout(request):
    #用户退出
    logout(request)
    return redirect('article:article_list')

def user_register(request):
    if request.method =="POST":
        user_register_form = UserRegisterForm(data=request.POST)
        print(user_register_form.is_valid())
        error = user_register_form.errors
        print(user_register_form.errors)
        print(str(user_register_form['username']))
        print(str(user_register_form['password1']))
        print(str(user_register_form['password2']))
        if user_register_form.is_valid():
            # 直接保存，并赋值给new_user
            new_user = user_register_form.save()
            login(request,new_user)
            return redirect('article:article_list')
        else:
            #输入密码不规范都会被检测为invalid，而不仅仅是密码不相同
            return render(request, 'userprofile/error.html',context={'error':error})
    # 如果get方法访问，也就是第一次进入页面：
    elif request.method == "GET":
        # 传入一个空表单
        user_register_form = UserRegisterForm()
        # 传入上下文并生成页面
        context={'form':user_register_form}
        return render(request,'userprofile/register.html',context)
    else:
        return HttpResponse("请使用GET或者POST请求")

# @login_required是一个Python装饰器。装饰器可以在不改变某个函数内容的前提下，给这个函数添加一些功能。
# 具体来说就是@login_required要求调用user_delete()函数时，用户必须登录；
# 如果未登录则不执行函数，将页面重定向到/accounts/login/地址去。
@login_required(login_url='/accounts/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登录用户、待删除用户是否相同
        if request.user == user:
            #退出登录，删除数据并返回博客列表
            logout(request)
            # 装饰器确定用户登录后，允许调用user_delete().
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("你没有删除操作的权限。")
    else:
        return HttpResponse("仅接受post请求。")

@login_required(login_url='/accounts/login/')
def profile_edit(request,id):
    user = User.objects.get(id=id)

    # user_id 是OneToOneField 自动生成的字段，用来表征两个数据库的关联
    # 这段代码通过查找user_id定位到对应的profile
    profile = Profile.objects.get(user_id=id)

    if request.method == 'POST':
        # 验证修改数据者是否为用户本人
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息。")
        profile_form = ProfileForm(data=request.POST,files=request.FILES,instance=profile)
        if profile_form.is_valid():
            # 取得清洗后的合法数据，还是一个字典
            profile_cd = profile_form.cleaned_data
            # 对字典按键取值并给profile，由profile完成保存
            profile.phone=profile_cd['phone']
            profile.bio=profile_cd['bio']

            # 如果 request.FILES 存在文件，则保存"avatar"的值
            if 'avatar' in request.FILES:
                # 注意profile.avatar 保存的是 图片路径
                profile.avatar = profile_cd["avatar"]
            profile.save()
            # 带参数redirect页面
            return redirect('article:article_list')
        else:
            return HttpResponse("注册表单输入有误，请重新输入~")
    elif request.method == 'GET':
        profile_form = ProfileForm()
        print(profile.avatar if profile.avatar else "No picture")
        context = {'profile':profile,'user':user}
        return render(request,'userprofile/edit.html',context)
    else:
        return HttpResponse("请使用GET或者POST请求")

userprofile/templates/userprofile/edit.html
{% extends "base.html" %}

{% block title %} 用户信息 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <div class="col-md-4">用户名: {{ user.username }}</div>
                <br>
                <form method="post" action="." enctype="multipart/form-data" >
                    {% csrf_token %}
                    {% if profile.avatar %}
                        <div class="col-md-4">头像</div>
                        <img src="{{ profile.avatar.url }}" style="max-width: 20%;border-radius: 10px;"
                             class="img-responsive">
                    {% else %}
                        <h5 class="col-md-4">暂无头像</h5>
                    {% endif %}
                <br>
                <br>
                    <!--avatar-->
                    <div class="form-group">
                        <label for="avatar" class="m-1">上传头像</label>
                        <br>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>
                    <!-- phone -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>
                    <!-- bio -->
                    <div class="form-group col-md-4">
                        <label for="bio">简介</label>
                        <textarea type="text" class="form-control" id="bio" name="bio"
                                  rows="12">{{ profile.bio }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

userprofile/templates/userprofile/error.html
{#依然继承base.html#}
{% extends "base.html" %}

{% block title %} 错误信息提示 {% endblock title %}

{% block content %}
    {# bootstrap常见的容器类 #}
    <div class="container">
        <div class="row">
            {#  不让html乱转义#}
            {{ error|safe }}
        </div>
    </div>
{% endblock %}

userprofile/templates/userprofile/login.html
{% extends "base.html" %}

{% block title %} 登录 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            {#没有账号时的注册#}
            <div class="col-12">
                <br>
                <h5>这是登录页面，还没有账号？</h5>
                <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
            </div>

            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {# action="."表示提交至当前页面 #}
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                        {# 输入密码表单的type="password"，可以让输入密码的时候显示小圆点，避免有人偷窥。#}
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>


        </div>
    </div>
{% endblock content %}

userprofile/templates/userprofile/register.html
{# 可以继承位于article文件夹的base.html #}
{% extends "base.html" %}

{% block title %} 注册账号 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
{#                <form method="post" action="." class="g-3">#}
{#                    {% csrf_token %}#}
{#                    {{ form.as_p }}#}
{#                    <button type="submit" class="btn layui-btn-primary" value="register">提交</button>#}
{#                </form>#}

                <form method="post" action="." class="signup-form">
                    {% csrf_token %}
                    <div class="alert alert-dark">
                        <label for="{{ form.username.id_for_label }}" class="text-justify text-black ">用户名:</label>
                        {{ form.username}}
                    </div>
                    <div class="alert alert-dark">
                        <label for="{{ form.email.id_for_label }}" class="text-justify text-black ">邮箱:</label>
                        {{ form.email }}
                    </div>
                    <div class="alert alert-dark">
                        <label for="{{ form.password1.id_for_label }}" class="text-justify text-black ">密码:</label>
                        {{ form.password1 }}
                    </div>
                    <div class="alert alert-dark">
                        <label for="{{ form.password2.id_for_label }}" class="text-justify text-black ">请再次输入以确认密码:</label>
                        {{ form.password2 }}
                        {% if form.password2.errors %}
                            <div class="invalid-feedback" >{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn btn-dark btn-lg" value="register">注册账户</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}