article/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
from my_blog import urls
from .views import article_list


app_name = 'article'

urlpatterns = [
    path('',views.index,name='index'),
    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article_create/',views.article_create,name='article_create'),
    path('article_delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article_update/<int:id>/',views.article_update,name='article_update'),
    path('increase-likes/<int:id>/',views.IncreaseLikesView.as_view(), name='increase_likes'),
]

comment/urls.py
# 博文id + 评论id
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns=[
    path('',views.index,name='index'),
    path('article/<int:article_id>',views.create_article_comment,name='create_article_comment'),
    path('article/<int:article_id>/<int:parent_comment_id>',views.create_article_comment,name='comment_reply'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import include,path,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from article.views import article_list

urlpatterns = [
    path("",article_list,name="home"),
    path("admin/", admin.site.urls),
    path("article/", include("article.urls",namespace="article")),
    path('userprofile/', include('userprofile.urls',namespace='userprofile')),
    path('comment/', include('comment.urls',namespace='comment')),
    # 这里的notifications.urls没有像之前一样用字符串，是为了确保模块安装到正确的命名空间中。
    path('inbox/notifications',include(notifications.urls,namespace='notifications')),
    # notice
    path('notice/',include('notice.urls',namespace='notice')),
    # allauth的登录，也是一个单独的APP
    path('accounts/', include('allauth.urls')),

    # 部署时使用，让gunicorn知道static和media文件在哪
    re_path(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

#添加这行为以后上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

app_name='notice'

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

article/models.py
from django.db import models
# 导入内建的User模型
from django.contrib.auth.models import User
from django.urls import reverse

# timezone用于处理时间相关事务
from django.utils import timezone
# 一个处理多对多关系的管理器：
from taggit.managers import TaggableManager
# 导入pillow库处理标题图
from PIL import Image


# 博客文章分栏
class ArticleColumn(models.Model):
    title = models.CharField(max_length=200)
    # 创建时间
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # __str__方法定义了需要表示数据时应该显示的名称。
        # return self.title 将文章标题返回
        return self.title


# 博客文章的数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # Django具有一个简单的账号系统（User），满足一般网站的用户相关的基本功能。

    # 文章所属栏目
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, null=True, blank=True, related_name="articles")
    # 文章标签
    tags = TaggableManager(blank=True)

    # 设置文章浏览量，初始值为0.
    total_views = models.PositiveIntegerField(default=0)

    # 文章标题.models.CharField为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=200)

    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d', blank=True, null=True)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    # 点赞数量
    likes = models.PositiveIntegerField(default=0)
    
    # 重载save()函数
    def save(self, *args, **kwargs):
        # 调用父类(models.Model)的save()功能
        # 即将model中的字段数据保存到数据库中，这里如果有图片也会保存，之后的修改基于已经保存过的图片。
        article = super(ArticlePost, self).save(*args, **kwargs)

        # 上方代码刚刚保存图片进数据库，现在基于它修改，
        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            img = Image.open(self.avatar.path)
            (x, y) = img.size
            new_x = 400
            new_y = int(new_x * (y / x))
            # Image.ANTIALIAS表示缩放采用平滑滤波。
            img = img.resize((new_x, new_y), Image.ANTIALIAS)
            img.save(self.avatar.path)
        # 最后一步，将父类save()
        # 返回的结果原封不动的返回去。
        return article

    # 文章正文。保存大量文本使用TextField
    content = models.TextField()

    # 文章的创建时间。参数 default=timezone.now()指定创建文章时将默认写入当前的时间
    created_time = models.DateTimeField(default=timezone.now)

    # 文章更新时间。 参数 auto_now=True指定每次更新数据时自动写入当前时间
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:  # class Meta提供元数据，也就是内部数据，这些信息不是某篇文章私有，而是整张表的共同行为。
        # ordering 指定模型返回的数据的排列顺序
        # "-created_time"表示返回数据应以创建时间倒序排列
        ordering = ('-created_time',)
        # 注意ordering是元组，括号中只含一个元素时不要忘记末尾的逗号。

    def was_created_recently(self):
        # 若文章是最近发表的，则返回True
        diff = timezone.now() - self.created_time
        if diff.days == 0 and 0 <= diff.seconds < 60:
            return True
        else:
            return False

    def __str__(self):
        # __str__方法定义了需要表示数据时应该显示的名称。
        # return self.title 将文章标题返回
        return self.title

article/forms.py
# 许多不同类型的数据可能需要在一张表单中准备显示，
# 渲染成HTML，使用方便的界面进行编辑，传到服务器，验证和清理数据，
# 然后保存或跳过进行下一步处理。
# Django的表单功能可以简化上述工作的大部分内容，
# 并且也能比大多数程序员自己编写代码去实现来的更安全。

from django import forms

from .models import ArticlePost

#写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明模型数据来源
        model = ArticlePost
        #指明要显示的字段
        fields = ['title', 'content','column','tags','avatar']

article/views.py
# @login提示登录，用在修改文章
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# 通过render函数，从模板生成网页;redirect重定向
from django.shortcuts import render
from django.urls import reverse

# 导入数据模型ArticlePost
from .models import ArticlePost, ArticleColumn
# 导入markdown2html的库
import markdown

from django.http import HttpResponse, HttpResponseRedirect

from .forms import ArticlePostForm

# 引入分页
from django.core.paginator import Paginator

from comment.forms import ArticleCommentForm

#类视图
from django.views import View


def index(request):
    return HttpResponse("Hello, world. You're at the article index.")


def article_list(request):
    # 如果search 不存在会设置为None
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    # print(column)
    tag = request.GET.get('tag')

    # 初始化查询集
    article_listing = ArticlePost.objects.all()
    # 按搜索
    if search:
        # 引入 Q 对象完成联合搜索
        from django.db.models import Q
        # 注意Q对象，Q(title__icontains=search)
        # 意思是在模型的title字段查询，icontains是不区分大小写的包含，中间用两个下划线隔开。
        # contains 区分大小写
        article_listing = article_listing.filter(Q(content__icontains=search) |
                                                 Q(title__icontains=search))

    else:
        # 将 search 参数重置为空
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit(): # isdigit()表示非负整数，因为这里是外键
        print("开始按栏目排序")
        article_listing = article_listing.filter(column=column)
    else:
        column = ''

    # 标签查询集
    # Django-taggit中标签过滤的写法：
    # filter(tags__name__in=[tag])，
    # 赋值的字符串tag用方括号包起来。
    # 因为django-taggit多标签联合查询时，代码为
    # Model.objects.filter(tags__name__in=["tag1", "tag2"])
    if tag and tag != 'None':
        article_listing = article_listing.filter(tags__name__in=[tag])

    # 查询集最后的排序，如果要求“最热”，则取出的文章按浏览量排列
    if order == 'hot':
        # - 表示倒序
        article_listing = article_listing.order_by("-total_views")

    # 引入paginator，每页1篇
    article_paginator = Paginator(article_listing, 3)
    # 网页展示为.../?page=1,get是用于获取页码的

    page_number = request.GET.get('page')
    # 将导航对象相应的页码内容返回，获取articles
    # 一些针对page_number的纠错paginator自己就有，不必多此一举。
    articles = article_paginator.get_page(page_number)

    # 在视图中通过Paginator类，给传递给模板的内容做了手脚：
    # 返回的不再是所有文章的集合，而是对应页码的部分文章的对象，并且这个对象还包含了分页的方法。
    return render(request, 'article/article_list.html',
                  context={"articles": articles,
                           'order': order,
                           'search': search,
                           'column': column})


def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    # 每次访问增加1的浏览量
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将content中markdown语法渲染成html样式
    md = markdown.Markdown(extensions=[
        # 包含 缩写、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        # 目录扩展
        'markdown.extensions.toc',
    ])
    article.content = md.convert(article.content)

    article_comments = article.article_comment.all()
    # 需要传递给模板的对象，虽然上面的语句改变了article.content，但是context中依然传入article就好。
    # 此外md.toc 算是个html对象，传入markdown的标题结构。
    # 第三，为了在评论中使用富文本，将评论的表单传到文章详情页面中

    article_comment_form = ArticleCommentForm()
    # print(article_comment_form)
    # print(article_comment_form.author)
    # 传入文章，大纲，评论，新建评论所用表单
    context = {'article': article, 'toc': md.toc, 'article_comments': article_comments,
               'article_comment_form':article_comment_form}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


@login_required(login_url='/accounts/login/')  # 需要登录
def article_create(request):
    # 判断用户是否提交数据
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        # 包括标题图，所以给了个file
        article_post_form = ArticlePostForm(data=request.POST, files=request.FILES)
        print(article_post_form.is_valid())  # False
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中。
            new_article_post = article_post_form.save(commit=False)

            # 指定目前登录的用户为作者
            new_article_post.author = request.user
            # 将新文章保存到数据库中
            print(new_article_post.author)
            new_article_post.save()

            # 保存 tags 的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return HttpResponseRedirect(reverse("article:article_list"))
        # 如果数据不合法，返回错误信息

    # 如果用户是get方法请求数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文,提交的表单和栏目
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'article/article_create.html', context=context)


@login_required(login_url='/accounts/login/')
def article_delete(request, id):
    # 以POST形式，否则别人用get可以直接删除
    if request.method == 'POST':
        # 取出相应的文章
        article = ArticlePost.objects.get(id=id)
        if request.user == article.author:
            # 将文章从数据库中删除
            article.delete()
            # 完成后返回到文章列表
            return HttpResponseRedirect(reverse("article:article_list"))
        else:
            return HttpResponse("只有作者才能删除")
    else:
        return HttpResponse("仅允许post请求")


@login_required(login_url='/accounts/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新title、content字段
    GET方法进入初始表单页面
    id:文章的id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)

    # 判断用户是否为POST提交表单数据
    if request.method == 'POST':
        # 创建表单来修改现有的article,data是POST方法传入的参数，用于更新表单。
        # instance让表单基于这篇文章操作，没有instance=article,就会新建一个对象！！我的五六篇文章就是这么得来的。
        article_post_form = ArticlePostForm(data=request.POST, files=request.FILES, instance=article)
        print(request.FILES)
        # 判断提交的数据是否符合表单的要求
        if article_post_form.is_valid():

            # 指定目前登录的用户为作者
            article_post_form.author = request.user

            # 指定标题图，如果有的话
            if request.FILES.get('avatar'):
                article_post_form.avatar = request.FILES.get('avatar')
                print(article_post_form.avatar)
            # 通过表单保存一篇新文章，并不向数据库提交(若提交了就会出现两个对象)
            # 如果想要在提交前增加更多属性，这是一种常规做法
            article_post_form = article_post_form.save(commit=False)
            # 指定标签，如果有的话
            if request.POST.get('tags'):
                article_post_form.tags.set(request.POST.get('tags').split(','), clear=True)
            else:
                article_post_form.tags.clear()
            article_post_form.save()
            # 完成后返回到这篇文章
            return HttpResponseRedirect(reverse("article:article_detail", kwargs={'id': id}))
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse(article_post_form.errors)

    # 如果用户是get方法请求数据，也就是通过"修改文章"按钮访问此页面
    else:
        # 只有作者本人才能修改
        if article.author == request.user:
            # 赋值上下文,提交的表单和栏目
            columns = ArticleColumn.objects.all()
            # 调用官方接口将文章的tags放进页面
            context = {'article': article, 'columns': columns,
                       'tags': ','.join([x for x in article.tags.names()]) or ""}
            # 将响应返回到模板中
            return render(request, 'article/article_update.html', context=context)
        # 将get模块也设计得有些复杂，是防止坏用户直接猜到链接输入。
        else:
            return HttpResponse("只有作者才能修改")

# 类视图的点赞
# 点赞数 +1
class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')
        

article/templates/article/article_create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    新建文章(作者默认为登录用户)
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

    <div class="container">
        <div class="row mt-2">
            <div class="col-12">
                <!-- 提交文章的表单 -->
                <!-- action="."指定了表单提交的地址为默认的当前url -->
                <form method="post" action="." enctype="multipart/form-data">
                    <!-- Django中需要POST数据的地方都必须有csrf_token -->
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">文章标题</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title" required>
                        <!-- 此处的id=title对应了模型中的title字段 -->
                    </div>

                    <div class="form-group">
                        <label for="avatar">标题图</label>
                        <input type="file" name="avatar" id="avatar" class="form-control-file">
                    </div>

                    <!--设置文章栏目-->
                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select
                                name="column" id="column" class="form-control">
                            <option value="none">请选择栏目..</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <!--设置文章标签-->
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text"
                               class="form-control col-3"
                               id="tags"
                               name="tags"
                        >
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="content">文章正文</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="content" name="content" rows="12"
                                  required></textarea>

                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

article/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}



<!-- 写入 base.html 中定义的 content -->
{% block content %}

<script src="{% static 'prism/prism.js' %}"></script>

<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

{% include 'back_to_top_func.html' %}
<!-- 文章详情，这里开始容器 -->
<div class="container">
    <!--前情提要-->
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <h6 class="col-auto text-center">修改时间:{{ article.updated_time|date:'Y-m-d' }}</h6>
        {# class用于修饰样式，alert-success 表示绿色的alert #}
        <div class="col-12 alert alert-success">作者：{{ article.author }}
            {#    调用的confirm_delete()函数在下方js #}
            {% if user == article.author %}
                <a class="btn btn-primary" href="{% url "article:article_update" article.id %}"> 修改文章</a>
                <a class="btn btn-danger" onclick="confirm_delete()"> 删除文章</a>
            {% endif %}
            浏览量：{{ article.total_views }}
        </div>
    </div>

    <!--文章正文，评论(一共占9列)，目录(单独占3列)-->
    <div class="row">
        <!-- 文章正文，占9栏,这个9栏很长哦 -->
        <div class="col-9 main-content">
            {#  这里加上|safe防止html乱转义#}
            <p>{{ article.content|safe }}</p>

            <div style="text-align:center;" class="mt-4">
                <button class="btn btn-outline-danger"
                        type="button"
                        onclick="validate_is_like(
                                 '{% url 'article:increase_likes' article.id %}',
                                 {{ article.id }},
                                 {{ article.likes }}
                                 )"
                        >
                <span>点赞</span>
                <span>
                    <i class="bi bi-hand-thumbs-up"></i>
                </span>
                <span id="likes_number">
                    {{ article.likes }}
                </span>
                </button>
            </div>
            <form method="post" action="{% url "comment:create_article_comment" article.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <label for="comment">我也要发言</label>
                    <!-- 这个只是简单输入文字<textarea type="text" class="form-control" id="comment" name="comment" rows="5"
                              cols="4"></textarea>-->
                    <div>
                        {{ article_comment_form.media }}
                        {{ article_comment_form.comment |safe }}
                    </div>
                </div>
                <!--提交按钮还得有-->
                <button type="submit" class="btn btn-primary">发表评论</button>
            </form>
        </div>

        <!-- 文章的目录，占3栏 -->
        <div class="col-3">
            <div class="sidebar">
                <div class="sidebar__inner">
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>

    <!-- ## 展示当前文章关联的评论 -->
    <!-- 因为是树形评论不要漏了 load mptt_tags！ -->
    <div class="row">
            {% load mptt_tags %}
            <h4>共有{{ article_comments.count }}条评论</h4>
                <!--MPTT独有的遍历方法，替代之前的for循环-->
                {% recursetree article_comments %}
                <!--给node 取个别名 comment-->
                {% with comment=node %}
                {#                {% for comment in article.article_comment.all %}#}
                <!--hr是一根横线-->
                <hr>
                <!--p中整体为一个段落，不换行-->
            <div class="{% if comment.reply_to %} offset-1 col-8
                        {% else %}
                        col-9 {% endif %}" id="comment_elem_{{ comment.id }}" >
{#                <p>#}
                    <!--strong为粗体-->
                    <strong style="color: pink">
                        {{ comment.author }}
                    </strong>

                    {% if comment.reply_to %}
                        <i class="bi bi-arrow-right"
                           style="color: cornflowerblue;"
                        ></i>
                        <strong style="color: pink">
                            {{ comment.reply_to }}
                        </strong>
                    {% endif %}

{#                </p>#}
                    <div style="font-family: inherit; font-size: 1em;">
                        {# 黑色字体的评论内容#}
                        {{ comment.comment|safe }}
                    </div>
                <!--span本身并不代表什么，用于group items-->
                    <span style="color: green">发布于:{{ comment.created|date:"Y-m-d H:i" }}
                             </span>
                <!--判断用户是否登录，没登录就跳至登录页-->
            {% if user.is_authenticated %}
            <!--这里button的onclick属性是加载出一个弹窗-->
            <button type="button"
                    class="btn btn-light btn-sm text-muted"
                    onclick="load_modal({{ article.id }},{{ comment.id }})">回复</button>
            {% else %}
            <a class="btn btn-light btn-sm text-muted"
                       href="{% url 'account_login' %}"
                       >回复</a>
            {% endif %}

        <!-- Modal -->
                <div class="modal fade"
                     id="comment_{{ comment.id }}"
                     tabindex="-1"
                     role="dialog"
                     aria-labelledby="CommentModalCenter"
                     aria-hidden="true"
                >
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content" style="height: 480px">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                            </div>
                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                        </div>

                    </div>
                </div>

                {% if not comment.is_leaf_node %}
                    <div class='children'>
                        {{ children }}
                    </div>
                {% endif %}
            </div>
            {% endwith %}
    {% endrecursetree %}

        </div>

    <!-- 新增一个隐藏的表单，用于删除 -->
    <form
            style="display:none;"
            id="safe_delete"
            action="{% url 'article:article_delete' article.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function confirm_delete() {
            var layer = layui.layer;

            // Create a prompt box with the "yes" button
            layer.confirm('是否确定删除？', {
                btn: ['是的', '不是'] // Specify the text for the buttons
            }, function execute_delete() {
                // If the user clicks "Yes", execute this function
                layer.msg('你确认删除了！');
                sleep(2000).then(() => {
                    document.querySelector('form#safe_delete button').click();
                    {#location.href = '{% url "article:article_delete" article.id %}'#}
                })

            }, function () {
                // If the user clicks "No", execute this function
                layer.msg('你还要再想想');
            });
        }
        function post_reply_and_show_it(new_comment_id) {
        // let定义一个 字符串变量;let定义的变量只在块内有效，且不能再次定义
        // 与之相对，var定义的变量，后面的会覆盖掉前面的。
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        // 函数中运用了JavaScript的三元运算符a ? b : c，翻译成人话就是：如果a成立则返回b，如果a不成立就返回c。作用是去掉url尾部的/，
            // 否则锚点不会生效。你可能会问，三元运算符多麻烦，为什么不直接把url末尾一个字符剔除掉呢？
            // 答案是这样写代码更加健壮。万一哪天Django解析的url尾部没有斜杠了呢。
        next_url = next_url.charAt(next_url.length - 1) === '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点，这个函数自带刷新并重定向页面。
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
        console.log(next_url)
        }
    </script>


</div>
    {% endblock content %}

    {% block script %}
        <!--它只是让侧边栏粘附，文章大纲在md.toc-->
        <script src="{% static 'sticky-sidebar/sticky-sidebar.js' %}"></script>
        <script type="text/javascript">
            var sidebar = new StickySidebar('.sidebar', {
                topSpacing: 20,
                bottomSpacing: 20,
                containerSelector: '.main-content',
                innerWrapperSelector: '.sidebar__inner'
            });
        </script>

        <!--新增代码，唤起二级回复的modal-->
        <script>
        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/article/' +
                    article_id + '/' +
                    comment_id + '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
                $(modal_body).append(content);
            }

            $(modal_id).modal('show');
        }
        </script>

        <!-- 新增代码，返回 -->
        <!-- csrf token -->
        <script src="{% static 'csrf.js' %}"></script>
        <script>
            // 点赞功能主函数
            function validate_is_like(url, id, likes) {
                // 取出 LocalStorage 中的数据
                let storage = window.localStorage;
                const storage_str_data = storage.getItem("my_blog_data");
                let storage_json_data = JSON.parse(storage_str_data);
                // 若数据不存在，则创建空字典
                if (!storage_json_data) {
                    storage_json_data = {}
                };
                // 检查当前文章是否已点赞。是则 status = true
                const status = check_status(storage_json_data, id);
                if (status) {
                    layer.msg('已经点过赞了哟~');
                    // 点过赞则立即退出函数
                    return;
                } else {
                    // 用 Jquery 找到点赞数量，并 +1
                    $('span#likes_number').text(likes + 1).css('color', '#dc3545');
                }
                // 用 ajax 向后端发送 post 请求
                $.post(
                    url,
                    // post 只是为了做 csrf 校验，因此数据为空
                    {},
                    function(result) {
                        if (result === 'success') {
                            // 尝试修改点赞数据
                            try {
                                storage_json_data[id] = true;
                            } catch (e) {
                                window.localStorage.clear();
                            };
                            // 将字典转换为字符串，以便存储到 LocalStorage
                            const d = JSON.stringify(storage_json_data);
                            // 尝试存储点赞数据到 LocalStorage
                            try {
                                storage.setItem("my_blog_data", d);
                            } catch (e) {
                                // code 22 错误表示 LocalStorage 空间满了
                                if (e.code === 22) {
                                    window.localStorage.clear();
                                    storage.setItem("my_blog_data", d);
                                }
                            };
                        } else {
                            layer.msg("与服务器通信失败..过一会儿再试试呗~");
                        }
        
                    }
                );
            };
        
            // 辅助点赞主函数，验证点赞状态
            function check_status(data, id) {
                // 尝试查询点赞状态
                try {
                    if (id in data && data[id]) {
                        return true;
                    } else {
                        return false;
                    }
                } catch (e) {
                    window.localStorage.clear();
                    return false;
                };
            };
        </script>


    {% endblock script %}