article/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
from my_blog import urls
from .views import article_list


app_name = 'article'

urlpatterns = [
    path('',views.index,name='index'),
    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article_create/',views.article_create,name='article_create'),
    path('article_delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article_update/<int:id>/',views.article_update,name='article_update'),
    path('increase-likes/<int:id>/',views.IncreaseLikesView.as_view(), name='increase_likes'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import include,path,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from article.views import article_list

urlpatterns = [
    path("",article_list,name="home"),
    path("admin/", admin.site.urls),
    path("article/", include("article.urls",namespace="article")),
    path('userprofile/', include('userprofile.urls',namespace='userprofile')),
    path('comment/', include('comment.urls',namespace='comment')),
    # 这里的notifications.urls没有像之前一样用字符串，是为了确保模块安装到正确的命名空间中。
    path('inbox/notifications',include(notifications.urls,namespace='notifications')),
    # notice
    path('notice/',include('notice.urls',namespace='notice')),
    # allauth的登录，也是一个单独的APP
    path('accounts/', include('allauth.urls')),

    # 部署时使用，让gunicorn知道static和media文件在哪
    re_path(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

#添加这行为以后上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

app_name='notice'

urlpatterns = [
    # 通知列表
    path("list/",views.CommentNoticeListView.as_view(),name="list"),
    # 更新通知状态
    path("update/",views.CommentNoticeUpdateView.as_view(),name="update"),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>',views.user_delete,name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
# 导入内建的User模型
from django.contrib.auth.models import User
from django.urls import reverse

# timezone用于处理时间相关事务
from django.utils import timezone
# 一个处理多对多关系的管理器：
from taggit.managers import TaggableManager
# 导入pillow库处理标题图
from PIL import Image


# 博客文章分栏
class ArticleColumn(models.Model):
    title = models.CharField(max_length=200)
    # 创建时间
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # __str__方法定义了需要表示数据时应该显示的名称。
        # return self.title 将文章标题返回
        return self.title


# 博客文章的数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # Django具有一个简单的账号系统（User），满足一般网站的用户相关的基本功能。

    # 文章所属栏目
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, null=True, blank=True, related_name="articles")
    # 文章标签
    tags = TaggableManager(blank=True)

    # 设置文章浏览量，初始值为0.
    total_views = models.PositiveIntegerField(default=0)

    # 文章标题.models.CharField为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=200)

    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d', blank=True, null=True)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    # 点赞数量
    likes = models.PositiveIntegerField(default=0)
    
    # 重载save()函数
    def save(self, *args, **kwargs):
        # 调用父类(models.Model)的save()功能
        # 即将model中的字段数据保存到数据库中，这里如果有图片也会保存，之后的修改基于已经保存过的图片。
        article = super(ArticlePost, self).save(*args, **kwargs)

        # 上方代码刚刚保存图片进数据库，现在基于它修改，
        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            img = Image.open(self.avatar.path)
            (x, y) = img.size
            new_x = 400
            new_y = int(new_x * (y / x))
            # Image.ANTIALIAS表示缩放采用平滑滤波。
            img = img.resize((new_x, new_y), Image.ANTIALIAS)
            img.save(self.avatar.path)
        # 最后一步，将父类save()
        # 返回的结果原封不动的返回去。
        return article

    # 文章正文。保存大量文本使用TextField
    content = models.TextField()

    # 文章的创建时间。参数 default=timezone.now()指定创建文章时将默认写入当前的时间
    created_time = models.DateTimeField(default=timezone.now)

    # 文章更新时间。 参数 auto_now=True指定每次更新数据时自动写入当前时间
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:  # class Meta提供元数据，也就是内部数据，这些信息不是某篇文章私有，而是整张表的共同行为。
        # ordering 指定模型返回的数据的排列顺序
        # "-created_time"表示返回数据应以创建时间倒序排列
        ordering = ('-created_time',)
        # 注意ordering是元组，括号中只含一个元素时不要忘记末尾的逗号。

    def was_created_recently(self):
        # 若文章是最近发表的，则返回True
        diff = timezone.now() - self.created_time
        if diff.days == 0 and 0 <= diff.seconds < 60:
            return True
        else:
            return False

    def __str__(self):
        # __str__方法定义了需要表示数据时应该显示的名称。
        # return self.title 将文章标题返回
        return self.title

article/forms.py
# 许多不同类型的数据可能需要在一张表单中准备显示，
# 渲染成HTML，使用方便的界面进行编辑，传到服务器，验证和清理数据，
# 然后保存或跳过进行下一步处理。
# Django的表单功能可以简化上述工作的大部分内容，
# 并且也能比大多数程序员自己编写代码去实现来的更安全。

from django import forms

from .models import ArticlePost

#写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明模型数据来源
        model = ArticlePost
        #指明要显示的字段
        fields = ['title', 'content','column','tags','avatar']

article/views.py
# @login提示登录，用在修改文章
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# 通过render函数，从模板生成网页;redirect重定向
from django.shortcuts import render
from django.urls import reverse

# 导入数据模型ArticlePost
from .models import ArticlePost, ArticleColumn
# 导入markdown2html的库
import markdown

from django.http import HttpResponse, HttpResponseRedirect

from .forms import ArticlePostForm

# 引入分页
from django.core.paginator import Paginator

from comment.forms import ArticleCommentForm

#类视图
from django.views import View


def index(request):
    return HttpResponse("Hello, world. You're at the article index.")


def article_list(request):
    # 如果search 不存在会设置为None
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    # print(column)
    tag = request.GET.get('tag')

    # 初始化查询集
    article_listing = ArticlePost.objects.all()
    # 按搜索
    if search:
        # 引入 Q 对象完成联合搜索
        from django.db.models import Q
        # 注意Q对象，Q(title__icontains=search)
        # 意思是在模型的title字段查询，icontains是不区分大小写的包含，中间用两个下划线隔开。
        # contains 区分大小写
        article_listing = article_listing.filter(Q(content__icontains=search) |
                                                 Q(title__icontains=search))

    else:
        # 将 search 参数重置为空
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit(): # isdigit()表示非负整数，因为这里是外键
        print("开始按栏目排序")
        article_listing = article_listing.filter(column=column)
    else:
        column = ''

    # 标签查询集
    # Django-taggit中标签过滤的写法：
    # filter(tags__name__in=[tag])，
    # 赋值的字符串tag用方括号包起来。
    # 因为django-taggit多标签联合查询时，代码为
    # Model.objects.filter(tags__name__in=["tag1", "tag2"])
    if tag and tag != 'None':
        article_listing = article_listing.filter(tags__name__in=[tag])

    # 查询集最后的排序，如果要求“最热”，则取出的文章按浏览量排列
    if order == 'hot':
        # - 表示倒序
        article_listing = article_listing.order_by("-total_views")

    # 引入paginator，每页1篇
    article_paginator = Paginator(article_listing, 3)
    # 网页展示为.../?page=1,get是用于获取页码的

    page_number = request.GET.get('page')
    # 将导航对象相应的页码内容返回，获取articles
    # 一些针对page_number的纠错paginator自己就有，不必多此一举。
    articles = article_paginator.get_page(page_number)

    # 在视图中通过Paginator类，给传递给模板的内容做了手脚：
    # 返回的不再是所有文章的集合，而是对应页码的部分文章的对象，并且这个对象还包含了分页的方法。
    return render(request, 'article/article_list.html',
                  context={"articles": articles,
                           'order': order,
                           'search': search,
                           'column': column})


def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    # 每次访问增加1的浏览量
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将content中markdown语法渲染成html样式
    md = markdown.Markdown(extensions=[
        # 包含 缩写、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        # 目录扩展
        'markdown.extensions.toc',
    ])
    article.content = md.convert(article.content)

    article_comments = article.article_comment.all()
    # 需要传递给模板的对象，虽然上面的语句改变了article.content，但是context中依然传入article就好。
    # 此外md.toc 算是个html对象，传入markdown的标题结构。
    # 第三，为了在评论中使用富文本，将评论的表单传到文章详情页面中

    article_comment_form = ArticleCommentForm()
    # print(article_comment_form)
    # print(article_comment_form.author)
    # 传入文章，大纲，评论，新建评论所用表单
    context = {'article': article, 'toc': md.toc, 'article_comments': article_comments,
               'article_comment_form':article_comment_form}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


@login_required(login_url='/accounts/login/')  # 需要登录
def article_create(request):
    # 判断用户是否提交数据
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        # 包括标题图，所以给了个file
        article_post_form = ArticlePostForm(data=request.POST, files=request.FILES)
        print(article_post_form.is_valid())  # False
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中。
            new_article_post = article_post_form.save(commit=False)

            # 指定目前登录的用户为作者
            new_article_post.author = request.user
            # 将新文章保存到数据库中
            print(new_article_post.author)
            new_article_post.save()

            # 保存 tags 的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return HttpResponseRedirect(reverse("article:article_list"))
        # 如果数据不合法，返回错误信息

    # 如果用户是get方法请求数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文,提交的表单和栏目
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'article/article_create.html', context=context)


@login_required(login_url='/accounts/login/')
def article_delete(request, id):
    # 以POST形式，否则别人用get可以直接删除
    if request.method == 'POST':
        # 取出相应的文章
        article = ArticlePost.objects.get(id=id)
        if request.user == article.author:
            # 将文章从数据库中删除
            article.delete()
            # 完成后返回到文章列表
            return HttpResponseRedirect(reverse("article:article_list"))
        else:
            return HttpResponse("只有作者才能删除")
    else:
        return HttpResponse("仅允许post请求")


@login_required(login_url='/accounts/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新title、content字段
    GET方法进入初始表单页面
    id:文章的id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)

    # 判断用户是否为POST提交表单数据
    if request.method == 'POST':
        # 创建表单来修改现有的article,data是POST方法传入的参数，用于更新表单。
        # instance让表单基于这篇文章操作，没有instance=article,就会新建一个对象！！我的五六篇文章就是这么得来的。
        article_post_form = ArticlePostForm(data=request.POST, files=request.FILES, instance=article)
        print(request.FILES)
        # 判断提交的数据是否符合表单的要求
        if article_post_form.is_valid():

            # 指定目前登录的用户为作者
            article_post_form.author = request.user

            # 指定标题图，如果有的话
            if request.FILES.get('avatar'):
                article_post_form.avatar = request.FILES.get('avatar')
                print(article_post_form.avatar)
            # 通过表单保存一篇新文章，并不向数据库提交(若提交了就会出现两个对象)
            # 如果想要在提交前增加更多属性，这是一种常规做法
            article_post_form = article_post_form.save(commit=False)
            # 指定标签，如果有的话
            if request.POST.get('tags'):
                article_post_form.tags.set(request.POST.get('tags').split(','), clear=True)
            else:
                article_post_form.tags.clear()
            article_post_form.save()
            # 完成后返回到这篇文章
            return HttpResponseRedirect(reverse("article:article_detail", kwargs={'id': id}))
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse(article_post_form.errors)

    # 如果用户是get方法请求数据，也就是通过"修改文章"按钮访问此页面
    else:
        # 只有作者本人才能修改
        if article.author == request.user:
            # 赋值上下文,提交的表单和栏目
            columns = ArticleColumn.objects.all()
            # 调用官方接口将文章的tags放进页面
            context = {'article': article, 'columns': columns,
                       'tags': ','.join([x for x in article.tags.names()]) or ""}
            # 将响应返回到模板中
            return render(request, 'article/article_update.html', context=context)
        # 将get模块也设计得有些复杂，是防止坏用户直接猜到链接输入。
        else:
            return HttpResponse("只有作者才能修改")

# 类视图的点赞
# 点赞数 +1
class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')
        

article/templates/back_to_top_func.html
<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 2.5rem;
        height: 2.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 3rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 20px;
        height: 5px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /*鼠标放在按钮上会变蓝*/
    .toTop-arrow:hover {
        background-color: blue;
    }
</style>

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;" onclick="back_top()"></button>

<script>
    window.onscroll = () => {
        if (window.scrollY > 300) {// Replace "500" with your desired scroll distance
            document.getElementById("BackTop").style.display = "block";
            console.log("Scrolled more than 300 pixels!");
        }
        else {// Replace "500" with your desired scroll distance
            document.getElementById("BackTop").style.display = "none";
            console.log("Scrolled back,smaller than 300 pixels!");
        }
    }

    // 向上滚动的函数，直接用人家造好的轮子
    function back_top() {
        window.scrollTo({
            top: 0,
            behavior: "smooth"
        });
    }
</script>

article/templates/base.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
{% load static %}


<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    {# 设置初始大小为1.0#}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- 通过CDN引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
          integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
      rel="stylesheet"
      href="https://cdn.bootcdn.net/ajax/libs/bootstrap-icons/1.10.3/font/bootstrap-icons.min.css"
    />

    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'article/monokai.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
    <!--引入jquery.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
            integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}


    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!--引入js代码-->
    {% block script %}{% endblock script %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}

    <!--
        popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
        在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
        教程采用本地引入是为了让读者了解静态文件本地部署的流程。
    -->

</body>

</html>

article/templates/footer.html
<!--应该不要加<html>，其它<head>-->
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.jjzdeyouxiang.com 2018</p>
    </div>
</footer>

article/templates/header.html
<!-- 新增 -->

<!-- 引入notifications的模板标签 -->
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url "article:article_list" %}">文章列表</a>
                </li>
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <!-- 新增代码，通知计数 -->
                            {% if unread_count %}
                            <a class="dropdown-item" href="{% url "notice:list" %}">通知: <span class="badge bg-danger justify-content-center text-left"  >{{ unread_count }}</span></a>
                            {% endif %}

                            <li><a class="dropdown-item nav-link" href="{% url "article:article_create" %}">新建文章</a></li>
                            <li><a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a></li>
                            <li><a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a></li>
                            <li><a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a></li>
                        </ul>
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}

                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <!-- 新增代码，通知计数 -->
                            {% if unread_count %}
                            <a class="dropdown-item" href="{% url "notice:list" %}">通知: <span class="badge bg-danger justify-content-center text-left"  >{{ unread_count }}</span></a>
                            {% endif %}

                            <li><a class="dropdown-item nav-link" href="{% url "article:article_create" %}">新建文章</a></li>
                            <li><a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a></li>
                            <li><a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a></li>
                            <li><a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a></li>
                        </ul>
                    </div>
                    <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">登录</a>
                    </li>
                    <!-- if 语句在这里结束 -->
                {% endif %}

            </ul>
        </div>

    </div>
</nav>

{# 判断用户是否登录，不能放在这个header.html的头部，否则 整个导航栏都不显示啦#}
{% if user.is_authenticated %}
    {#   隐藏表单#}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">删除用户</button>
    </form>

    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function user_delete() {
            var layer = layui.layer;

            // Create a prompt box with the "yes" button
            layer.confirm('是否确定删除用户？', {
                btn: ['是的', '不是'] // Specify the text for the buttons
            }, function execute_delete() {
                // If the user clicks "Yes", execute this function
                layer.msg('你确认删除了！');
                sleep(2000).then(() => {
                    {# 这里指定form的id，并点击按钮#}
                    document.querySelector('form#user_delete button').click();
                    console.log('删除点击成功!');
                    {#location.href = '{% url "article:article_delete" article.id %}'#}
                })

            }, function () {
                // If the user clicks "No", execute this function
                layer.msg('你还要再想想');
            });
        }
    </script>

{% endif %}